### ISSUE TITLE
Priors in likelihood profiles (starter file specification)

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nwfsc-assess/nwfscDiag#16] opened 2022-05-25 17:38 UTC
@iantaylor-NOAA suggested that we create a new figure that has with the prior and without the prior. 🏆 for everyone!

If you fix the value you have a "point prior" because you are fixing it rather than the actual prior.
3 situations (@iantaylor-NOAA I missed this can you edit this comment)

**Comment by iantaylor-NOAA** [comment] 2022-05-25 17:41
Duplicate of https://github.com/nwfsc-assess/nwfscDiag/issues/6. I'll copy the comment over and close this.

**Closed by iantaylor-NOAA** 2022-05-25 17:41 UTC
Labels: duplicate, enhancement

**Comment by kellijohnson-NOAA** [comment] 2022-05-25 17:43
Thanks @iantaylor-NOAA sorry I didn't search the issues first.
